// Unified works index — the spine of the site.
//   m:    medium tags, written in MEDIA order (build-c.js) — that is display order
//   k:    kind (solo / group / duo / score / residency / release / dj set / technical / work)
//   x:    the exhibition or project this work was shown in, when it differs from the work title
//   w:    collaborator or collective
//   img:  grid thumbnail
//   slug: generates work-<slug>.html from `det`
//   det:  detail page payload — role, text, links, images
//   noHome: keep this work's thumbnail out of the home rotation
//   archiveOnly: archive material — shown on the archive page, not in the works index
module.exports = [
  { y: 2025, t: 'A World Observing a World', m: ['intermedia', 'video'], w: 'Hyeseon Han', v: '—', c: '', k: 'work', img: 'img/intermedia/a-world-observing-a-world.jpg', slug: 'a-world-observing-a-world', det: { role: 'Fictional documentary \u00b7 video, sound design', text: ['\u2039A World Observing a World\u203a is a fictional documentary that imagines a probe sent from one extraterrestrial planet to explore another.', 'I wanted to take the meeting of \u201cself\u201d and \u201cother\u201d out of ordinary social interaction and raise it to a collision between two planets running on entirely different physical laws. Through the neutral gaze of an exploratory robot, the misunderstandings that arise between people become acts of observation and investigation \u2014 a way of turning what is personal into something that resonates collectively.', 'I made this with the media artist Hyeseon Han. We brought together imagined organisms from Planet A and exploratory robots from Planet B, built out of speculative readings of A\u2019s lifeforms, and set them in micro-scale sound environments \u2014 so the audience meets the \u201cother\u201d either through the probe\u2019s eyes or from outside it.', 'The slow visuals, the ambient atmospheres and the tactile sound are all there to open up how much can be perceived.', 'Every person is an independent world, one that can never be fully understood by anyone else. I imagined each of us as a separate planet, unknowable from outside, and documented the moment two of those worlds meet as a neutral exploratory documentary.'], video: [{ label: 'A World Observing a World', src: 'https://www.youtube.com/embed/a4u3DuX8KQg?rel=0&modestbranding=1' }, { label: 'A World Observing a World \u2014 Archive', src: 'https://www.youtube.com/embed/ptBruxQWJSA?rel=0&modestbranding=1' }], images: ['img/works/a-world-observing-a-world/01.png', 'img/works/a-world-observing-a-world/02.png', 'img/works/a-world-observing-a-world/03.png', 'img/works/a-world-observing-a-world/04.png', 'img/works/a-world-observing-a-world/05.png', 'img/works/a-world-observing-a-world/06.png', 'img/works/a-world-observing-a-world/07.png', 'img/works/a-world-observing-a-world/08.png', 'img/works/a-world-observing-a-world/09.png', 'img/works/a-world-observing-a-world/10.png', 'img/works/a-world-observing-a-world/11.png', 'img/works/a-world-observing-a-world/12.png', 'img/works/a-world-observing-a-world/13.png', 'img/works/a-world-observing-a-world/14.png', 'img/works/a-world-observing-a-world/15.png', 'img/works/a-world-observing-a-world/16.png', 'img/works/a-world-observing-a-world/17.png', 'img/works/a-world-observing-a-world/18.png', 'img/works/a-world-observing-a-world/19.png', 'img/works/a-world-observing-a-world/20.png', 'img/works/a-world-observing-a-world/21.png', 'img/works/a-world-observing-a-world/22.png', 'img/works/a-world-observing-a-world/23.png', 'img/works/a-world-observing-a-world/24.png', 'img/works/a-world-observing-a-world/25.png'] } },
  { y: 2025, t: 'Casa Carlotta', archiveOnly: true, m: ['photography'], v: 'Casa de Lollo', c: 'IT', k: 'residency', img: 'img/works/casa-carlotta/01.jpg', link: 'residency-archive.html#casa-carlotta' },
  { y: 2025, t: 'SelvArt', archiveOnly: true, m: ['sound', 'photography'], v: 'SelvArt Residency, Verona', c: 'IT', k: 'residency', link: 'residency-archive.html#selvart' },
  { y: 2025, t: 'Not One, Not Two', m: ['sound'], w: 'Sungyeon Kim', v: 'The Performance Kitchen, Copenhagen \u00b7 Studio Theatre, London', c: 'DK / UK', k: 'score', img: 'img/scores/not-one-not-two-1.jpg', slug: 'not-one-not-two', det: { role: 'I wrote the sound track for Sungyeon Kim\u2019s wearable object performances \u00b7 2024\u20132025', text: ['\u2039Not One, Not Two\u203a is Sungyeon Kim\u2019s somatic performance and sculptural environment, for which I wrote the sound. It reimagines the body not as an isolated entity, but as a cellular node within a larger ecology of movement, matter, and memory. Working with inflatable latex forms, metal installations, and choreographies of shared weight, the piece enacts a slow unfolding of relation between performers, objects, and the porous space they co-inhabit.'], links: [{ label: 'sungyeonkim.com', href: 'https://www.sungyeonkim.com' }], images: ['img/scores/not-one-not-two-1.jpg', 'img/scores/not-one-not-two-2.jpg', 'img/scores/not-one-not-two-3.jpg'] } },
  { y: 2025, t: 'The Trained Gaze', m: ['video'], v: 'G-Artience, Daejeon', c: 'KR', k: 'group', img: 'img/intermedia/the-trained-gaze.jpg', slug: 'the-trained-gaze', det: { role: 'Single-channel video, AI film' } },
  { y: 2025, t: 'at the barn: a listening party', m: ['sound', 'performance'], v: 'Seoul', c: 'KR', k: 'solo', slug: 'at-the-barn', det: { role: 'Listening session, spatial audio · 4DSOUND' } },

  { y: 2024, t: 'Kontakt Group presents Birth of Bea', m: ['sound', 'performance'], w: 'Laura Kampman', v: 'Garage Noord, Amsterdam', c: 'NL', k: 'group' },
  { y: 2024, t: 'Listening Session', m: ['sound', 'performance'], w: 'Laura Kampman', v: 'KODA, Schiedam', c: 'NL', k: 'solo' },
  { y: 2024, t: 'Patricas pillow', m: ['sound', 'performance'], w: 'Laura Kampman', v: 'Nachbar, Amsterdam', c: 'NL', k: 'solo' },
  { y: 2024, t: 'Pishu ‘Penguin’ Teaser', m: ['video'], v: '—', c: '', k: 'work', img: 'img/intermedia/pishu-penguin-teaser.png', slug: 'pishu-penguin-teaser', det: { role: 'Audiovisual teaser' } },
  { y: 2024, t: 'Waves Piece', m: ['sound', 'video', 'drawing'], w: 'Laura Kampman', v: 'Roof of Air', c: 'NL', k: 'release', img: 'img/intermedia/waves-piece.png', slug: 'waves-piece', det: { role: 'I played flute and electronics and made the graphic score and drawing; visuals with Ardemar', text: ['Co-written with Laura Kampman. I played flute and electronics and made the graphic score and the drawing; the visuals were made with Ardemar. It came out on Laura’s album ‘Coming into daily life’ (Roof of Air, 4 March 2024).'], links: [{ label: 'listen — bandcamp', href: 'https://roofofair.bandcamp.com/track/waves-piece' }, { label: 'watch — music video', href: 'https://youtu.be/U4oNkKf1BHU?feature=shared&t=557' }, { label: 'press — some other time', href: 'https://www.someothertime.co.uk/articles/laura-kampman-coming-into-daily-life' }, { label: 'press — instagram', href: 'https://www.instagram.com/p/C5HXRZ3I10j' }], images: ['img/works/waves-piece/01-graphic-score.jpg', 'img/works/waves-piece/02.jpg', 'img/works/waves-piece/03.jpg', 'img/works/waves-piece/04.jpg', 'img/works/waves-piece/05.jpg', 'img/works/waves-piece/06.jpg', 'img/works/waves-piece/07.jpg', 'img/works/waves-piece/08.jpg', 'img/works/waves-piece/09.jpg'] } },
  { y: 2024, t: 'Welcome to the Micro World', m: ['sound'], w: 'Sungyeon Kim', v: 'Platform Theatre, London', c: 'UK', k: 'score', slug: 'welcome-to-the-micro-world', det: { role: 'I wrote the sound track for Sungyeon Kim\u2019s performance work', text: ['A score I wrote for the stage \u2014 a listening environment scaled down to the size of a cell, then amplified until the room becomes the body.'], links: [{ label: 'sungyeonkim.com', href: 'https://www.sungyeonkim.com' }], audio: 'https://framerusercontent.com/assets/r6PQLwKFcvVtwvPkStRO4ynTHlA.mp3' } },

  { y: 2023, t: 'Bad van Geluid #1', m: ['sound', 'performance'], w: 'Laura Kampman', v: 'De Doelen Studio, Rotterdam', c: 'NL', k: 'group' },
  { y: 2023, t: 'Mulsori', m: ['sound', 'intermedia', 'performance'], v: 'LPM Festival 2023, Münster', c: 'DE', k: 'solo', img: 'img/intermedia/mulsori.png', slug: 'mulsori', det: { role: 'Audiovisual performance, composition · 20 min', text: ['I made the images of water from point clouds I collected with a lidar sensor in a wood near where I live. Then I synthesised and recorded sound from the sound of water — mulsori — until the two became a twenty-minute audiovisual piece.'], links: [{ label: 'watch — LPM 2023 A/V performance', href: 'https://youtu.be/AoPYxq40K-c' }], images: ['img/works/mulsori/01.jpg', 'img/works/mulsori/02.jpg', 'img/works/mulsori/03.jpg', 'img/works/mulsori/04.jpg', 'img/works/mulsori/05.jpg', 'img/works/mulsori/06.jpg', 'img/works/mulsori/07.jpg', 'img/works/mulsori/08.jpg', 'img/works/mulsori/09.jpg', 'img/works/mulsori/10.jpg'] } },
  { y: 2023, t: 'Rooms by Humans. Spaceless Echo', m: ['sound', 'intermedia', 'installation'], w: 'ARDEMAR', v: 'De Nijverheid, Utrecht', c: 'NL', k: 'group', img: 'img/intermedia/rooms-by-humans.png', slug: 'rooms-by-humans', det: { role: 'Interactive installation, composition', links: [{ label: 'watch', href: 'https://youtu.be/P3Ey23k0I_g' }] } },
  { y: 2023, t: 'Snow Sequence', m: ['intermedia'], w: 'Gerda', v: 'Veloso, Seoul', c: 'KR', k: 'group', img: 'img/intermedia/snow-sequence.jpg', slug: 'snow-sequence', det: { role: 'I made live audiovisual for the post-rock / ambient-folk band Gerda', images: ['img/works/snow-sequence/01.jpg', 'img/works/snow-sequence/02.jpg', 'img/works/snow-sequence/03.jpg', 'img/works/snow-sequence/04.jpg', 'img/works/snow-sequence/05.jpg'] } },
  { y: 2023, t: 'The Hangout — Le Guess Who? x Kapitaal x Stranded FM', m: ['sound', 'performance'], v: 'Utrecht', c: 'NL', k: 'dj set' },
  { y: 2023, t: 'WFS Concert', m: ['sound', 'intermedia', 'performance'], v: 'HKU IBB, Utrecht (ICLC 2023) · Zaal 100, Amsterdam', c: 'NL', k: 'solo', img: 'img/works/wfs-iclc/01.jpg', slug: 'wfs-concert', det: { role: 'Wave field synthesis, WFS Collider · compositions ‹dim› and ‹0204›', text: ['I presented two of my wave field synthesis compositions, ‹dim› and ‹0204›, at the International Conference on Live Coding 2023. WFS is a rendering technique made specifically for spatial audio.', '“To make sound is to be.” ‹0204› is an homage to my grandmother, built from recordings I made at her funeral. I performed it again at Zaal 100 on an eight-speaker setup.'], links: [{ label: 'listen — ‹0204› stereo mix', href: 'https://soundcloud.com/hh_cloud/0204-stereo-export/s-WCoJboOY6bl' }], images: ['img/works/wfs-iclc/01.jpg', 'img/works/score-0204/01.jpg'] } },
  { y: 2023, t: 'There’s no wifi in the barn', m: ['sound', 'performance'], w: 'd³ (deep drone dreamer)', v: 'World Music House Seoul, Seoul', c: 'KR', k: 'solo', link: 'release-theres-no-wifi-in-the-barn.html' },
  { y: 2023, t: 'When Doves Cry.. Rage in Eden', m: ['sound', 'intermedia', 'performance'], v: 'ACS, Seoul', c: 'KR', k: 'group', img: 'img/intermedia/when-doves-cry.jpg' },

  { y: 2022, t: 'Jeon-Yu-Um-Mu (專有陰霧)', m: ['intermedia', 'performance'], v: 'Gongsangondo, Seoul', c: 'KR', k: 'group', img: 'img/intermedia/junyueummu.jpg', slug: 'junyueummu', det: { role: 'I made live audiovisual for the electronic musicians Eeajik, Guineissik and Piano Shoegazer', images: ['img/works/junyueummu/01.jpg', 'img/works/junyueummu/02.jpg', 'img/works/junyueummu/03.jpg', 'img/works/junyueummu/04.jpg'] } },
  { y: 2022, t: 'LostAir × ZER01NE DAY', m: ['intermedia'], w: 'Lost Air', v: 'Seongsu S Factory D, Seoul', c: 'KR', k: 'technical', img: 'img/intermedia/zer01ne-day-lost-air.png', slug: 'lostair-zer01ne', det: { role: 'I did the data visualisation and VJing', text: ['“Lost Air × zer01ne day” was an audiovisual performance with two DJs and two VJs. I generated the visuals live in TouchDesigner; the point clouds were captured with a Leica BLK360 and a Velodyne lidar scanner.'], images: ['img/works/lostair-zer01ne/01.jpg', 'img/works/lostair-zer01ne/02.jpg', 'img/works/lostair-zer01ne/03.jpg', 'img/works/lostair-zer01ne/04.jpg', 'img/works/lostair-zer01ne/05.jpg'] } },
  { y: 2022, t: 'Rave Geometry Series', noHome: true, m: ['intermedia'], x: 'Project Hashtag', w: 'Lost Air', v: 'MMCA, Seoul', c: 'KR', k: 'group', img: 'img/intermedia/rave-geometry.jpg', slug: 'rave-geometry', det: { role: 'I worked as data-visual director, technical artist and assistant director · 2022–2023', text: ['An audiovisual interview series, roughly ten minutes each. I worked on ‹Rave Geometry (our, has never stopped)› by the Seoul-based collective Lost Air, shown at MMCA Seoul as part of Project Hashtag.'], links: [{ label: 'MMCA — exhibition', href: 'https://www.mmca.go.kr/eng/exhibitions/exhibitionsDetail.do?exhFlag=3' }, { label: 'press — IT동아 clip', href: 'https://youtu.be/ok89R7X0SG8' }], images: ['img/works/rave-geometry/01.jpg'] } },
  { y: 2022, t: 'Seoul Stage 11', m: ['intermedia', 'performance'], v: 'SAPY, Seoul', c: 'KR', k: 'group', img: 'img/works/seoul-stage-11/01.jpg', slug: 'seoul-stage-11', det: { role: 'Live visuals \u00b7 TouchDesigner \u00b7 two editions, June and August 2022', text: ['I made the live visuals for two editions of Seoul Stage 11 at SAPY. \u2039\ud478\ub978, \uc9d9\uc740, \uc5ec\ub984\u203a with the folk artist Zitten, and \u2039Jazz Breeze on a lazy morning\u203a with the jazz band Prelude.'], images: ['img/works/seoul-stage-11/01.jpg', 'img/works/seoul-stage-11/02.jpg'] } },
  { y: 2022, t: 'The Very First Cyborg', m: ['painting'], v: 'Gallery 175, Seoul', c: 'KR', k: 'group', href: 'https://www.karts.ac.kr/usr/shw/exh/selectUsrShowDetail.do?exNo=3254' },
  { y: 2022, t: 'avcd', m: ['video'], x: 'Catering Service', v: 'pixelcounting, Seoul', c: 'KR', k: 'group', img: 'img/intermedia/avcd.png', slug: 'avcd', det: { role: 'Single-channel video, sound design · Ableton Live, TouchDesigner', images: ['img/works/avcd/01.jpg', 'img/works/avcd/02.jpg'] } },
  { y: 2022, t: 'computing-composing', m: ['intermedia'], v: '—', c: '', k: 'work', img: 'img/intermedia/computing-composing.jpg', slug: 'computing-composing', det: { images: ['img/works/computing-composing/01.jpg', 'img/works/computing-composing/02.jpg', 'img/works/computing-composing/03.jpg', 'img/works/computing-composing/04.jpg', 'img/works/computing-composing/05.jpg'], role: 'Algorithmic audiovisual · TouchDesigner · about 1\u203236\u2033', text: ['Electronic tone and white noise stack up into chords, and over them random numbers drawn from an algorithm lay a rhythm and a melody that come out differently every time. The piece resonates through its devices and its noise, and is reborn in a new shape at each playing.'], links: [{ label: 'watch', href: 'https://youtu.be/XrHV-Am-aeI' }] } },
  { y: 2022, t: 'milk ’n fridge', m: ['intermedia', 'installation'], x: 'K-Arts in Osaka: Communication', w: 'Guinneissik', v: 'Osaka Korean Culture Center, Osaka', c: 'JP', k: 'group', img: 'img/intermedia/milk-n-fridge.jpg', slug: 'milk-n-fridge', det: { role: 'Audiovisual installation · video (colour, sound, interactive), four speakers · Ableton Live, TouchDesigner', text: ['A four-channel audiovisual installation I made with Guinneissik, shown in ‹K-Arts in Osaka: Communication› at the Osaka Korean Culture Center, 1–8 July 2022.'], links: [{ label: 'watch', href: 'https://youtu.be/fg-i-DqTCR0' }, { label: 'press — ADF Web Magazine', href: 'https://www.adfwebmagazine.jp/art/first-korean-student-media-art-open-call-exhibition-held-in-osaka' }], images: ['img/works/milk-n-fridge/01.jpg'] } },
  { y: 2022, t: '‘Dew on the eye’', m: ['photography', 'painting'], v: 'CICA Museum, Gimpo', c: 'KR', k: 'solo', img: 'img/karts/k19.jpg', slug: 'dew-on-the-eye', det: { role: 'Solo exhibition · painting', links: [{ label: 'kimiver.com — dew on the eye', href: 'https://kimiver.com/dew-on-the-eye' }, { label: 'kartsfaa — archive', href: 'https://kartsfaa.org/35026974' }], images: ['img/karts/k19.jpg', 'img/karts/k20.jpg', 'img/karts/k21.jpg', 'img/karts/k22.jpg', 'img/karts/k23.jpg'] } },
  { y: 2022, t: '‘dim’ music video', m: ['intermedia', 'video'], v: '—', c: '', k: 'work', img: 'img/intermedia/dim-music-video.png', slug: 'dim-music-video', det: { role: 'Interactive music video · Unity, Ableton Live', text: ['An interactive music video for my single ‹dim›, which I built in Unity as a walking simulator.'], links: [{ label: 'watch — MV', href: 'https://youtu.be/dOkqIAolvIY' }, { label: 'listen — bandcamp', href: 'https://kimiver.bandcamp.com/track/dim' }], images: ['img/works/dim/01.jpg', 'img/works/dim-music-video/01.jpg', 'img/works/dim-music-video/02.jpg'] } },

  { y: 2021, t: 'Duet / Trio for piano and computer', m: ['intermedia', 'performance'], v: '—', c: '', k: 'work', img: 'img/intermedia/duet-trio.png', w: 'guinneissik (Seokwoo Han)', slug: 'duet-trio', det: { images: ['img/works/duet-trio/01.jpg', 'img/works/duet-trio/02.jpg', 'img/works/duet-trio/03.jpg', 'img/works/duet-trio/04.jpg', 'img/works/duet-trio/05.jpg', 'img/works/duet-trio/06.jpg', 'img/works/duet-trio/07.jpg'], role: 'Physical computing, interactive performance · Arduino, MaxMSP · 25:16', text: ['Two ultrasonic sensors read the pianist\u2019s movement, turn it into numbers, and turn the numbers into sound. In three movements: two for piano and computer, the third for piano and two computers. Piano by guinneissik (Seokwoo Han).'], links: [{ label: 'watch', href: 'https://youtu.be/0XSWQC83J3I' }] } },
  { y: 2021, t: 'BETA TEST FOR AN-NYEONG (안녕을 위한 베타테스트)', m: ['painting'], x: '22nd Senior Exhibition', v: 'Korea National University of Arts, Seoul', c: 'KR', k: 'graduation', img: 'img/karts/k22.jpg', slug: 'beta-test-for-an-nyeong', det: { role: 'Graduation exhibition · painting', links: [{ label: 'read — 불가능한 대화 / Impossible Dialogues', href: 'text-impossible-dialogues.html' }, { label: 'kartsfaa — archive', href: 'https://kartsfaa.org/35026974' }], video: [{ label: 'Duet / Trio for Piano and Computer · 25:16', src: 'https://www.youtube.com/embed/0XSWQC83J3I?rel=0&modestbranding=1' }, { label: 'Till We Have Faces (얼굴 찾기) · 6:58', src: 'https://www.youtube.com/embed/J2mvTO9yCvE?rel=0&modestbranding=1' }], images: ['img/karts/k22.jpg', 'img/karts/k23.jpg', 'img/karts/k20.jpg', 'img/karts/k21.jpg', 'img/karts/k19.jpg'] } },
  { y: 2021, t: 'Jong-Dal Jong-Dal', m: ['painting'], v: 'K-Arts Bokdo Gallery, Seoul', c: 'KR', k: 'duo', href: 'https://youtu.be/UAhdYUyAOdM' },
  { y: 2021, t: '“meet me at 1.048596 :)”', m: ['intermedia', 'installation'], x: 'Persona Society (페르소나 사회)', w: 'Guinneissik', v: 'Seongbuk Young Art Space, Seoul', c: 'KR', k: 'group', img: 'img/intermedia/meet-me-at-1048596.png', slug: 'meet-me-at-1048596', det: { role: 'Interactive audiovisual installation', images: ['img/works/meet-me/01.jpg', 'img/works/meet-me/02.jpg', 'img/works/meet-me/03.jpg', 'img/works/meet-me/04.jpg', 'img/works/meet-me/05.jpg', 'img/works/meet-me/06.jpg', 'img/works/meet-me/07.jpg'], links: [{ label: 'Seongbuk Young Art Space — archive', href: 'https://sma.sbculture.or.kr/youngartspace/archive/reference.do?mode=view&articleNo=34430' }] } },

  { y: 2020, t: 'Behind the Scene / Stage 365를 위한 습작', m: ['video'], v: '—', c: '', k: 'work', img: 'img/works/behind-the-scene/01.jpg', slug: 'behind-the-scene', det: { images: ['img/works/behind-the-scene/01.jpg'], role: 'Single-channel video \u00b7 6\u203219\u2033', text: ['I read the construction site as a place where fiction is being built. Walking around Imun-dong I kept finding the tarpaulins of building sites tangled in with plants, rusted green containers and geometric objects sitting among fallen leaves and grass, and could not decide whether to see them as one thing or two.', 'Behind the tarpaulin a hillside neighbourhood was coming down, half dismantled, looking like a stage set left unfinished for the next act. In the emptied houses a dead lightbulb still hung, furniture stood uselessly, and stray cats and weeds had moved in. For Brecht, showing the stage was what put distance between the audience and the fiction.'], links: [{ label: 'watch', href: 'https://youtu.be/Bv6hgjoveLw' }] } },
  { y: 2020, t: 'Till We Have Faces (얼굴 찾기)', m: ['video'], v: '—', c: '', k: 'work', img: 'img/works/till-we-have-faces/01.jpg', slug: 'till-we-have-faces', det: { images: ['img/works/till-we-have-faces/01.jpg', 'img/works/till-we-have-faces/02.jpg', 'img/works/till-we-have-faces/03.jpg', 'img/works/till-we-have-faces/04.jpg', 'img/works/till-we-have-faces/05.jpg', 'img/works/till-we-have-faces/06.jpg', 'img/works/till-we-have-faces/07.jpg', 'img/works/till-we-have-faces/08.jpg', 'img/works/till-we-have-faces/09.jpg', 'img/works/till-we-have-faces/10.jpg', 'img/works/till-we-have-faces/11.jpg'], role: 'Short film \u00b7 6:58', links: [{ label: 'watch', href: 'https://youtu.be/J2mvTO9yCvE' }] } },

  { y: 2017, t: 'Le Gibet', m: ['video'], v: '—', c: '', k: 'work', img: 'img/works/le-gibet/01.jpg', slug: 'le-gibet', det: { images: ['img/works/le-gibet/01.jpg'], role: 'Short film', text: ['A visualisation of sound.'], links: [{ label: 'watch', href: 'https://youtu.be/a9zloB_4_ec' }] } },

  { y: 2016, t: 'Tearing Down (허물기)', m: ['video'], v: '—', c: '', k: 'work', img: 'img/works/heomulgi/01.jpg', slug: 'heomulgi', det: { images: ['img/works/heomulgi/01.jpg'], role: 'Short film', links: [{ label: 'watch', href: 'https://youtu.be/blSqSn20y-0' }] } }
];
